<?php
/**
 *
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>FishPig - Magento Development &amp; Extensions</title>
</head>
<body>
	<h1><?php echo $this->__('Suspected Bot') ?></h1>
	<p>Your activity suggests that you're  a bot. If this is incorrect, please <a href="/contacts/">get in touch</a>.</p>
</body>
</html>